logging.level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        transaction:
          interceptor: TRACE
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
      hibernate:
        SQL: DEBUG
        resource:
          transaction: DEBUG

# 트랜잭션이 커밋되었는지 롤백 되었는지 로그로 확인할 수 있다.